name: build-debian-unstable
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zapashcanon/gitea-ocaml-ci:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4

      - name: Cache opam switch
        uses: actions/cache@v4
        with:
          path: _opam
          key: opam-${{ hashFiles('ono.opam') }}
          restore-keys: opam-

      - name: test
        run: |
          set -x

          export HOME=/root

          # Prepare OCaml stuff
          eval "$(opam env)"
          export OPAMCONFIRMLEVEL=unsafe-yes
          opam update
          apt update

          # Install system and opam-repo dependencies
          opam install . --with-test --with-dev-setup --with-doc --deps-only

          # Build and test
          dune build @install
          dune runtest
