name: build-nix
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: nixos/nix:2.3.16
    steps:
      - uses: actions/checkout@v4

      - name: Cache nix store
        uses: actions/cache@v4
        with:
          path: /nix
          key: nix-${{ hashFiles('shell.nix') }}
          restore-keys: nix-

      - name: test
        run: |
          set -x

          nix-shell --run "
            ODOC_WARN_ERROR=true
            dune build @fmt &&
            dune build @doc &&
            dune build @install &&
            dune build @all &&
            dune runtest
          "

          nix-shell -p git --run "
            git diff --exit-code ono.opam
          "
